# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.1’

target 'ProSpinner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProSpinner

pod 'SpriteKit-Spring', :git => 'https://github.com/ataugeron/SpriteKit-Spring/'
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase/Messaging'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'JSSAlertView'
pod 'Google-Mobile-Ads-SDK'
pod 'XCGLogger', '~> 5.0.1'
pod 'SwiftyStoreKit'
pod 'SwiftGifOrigin', '~> 1.6.1'

  target 'ProSpinnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProSpinnerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
